name: Continuous Integration

on:
  push:
    branches: ["step-1", "step-2", "step-3"]
  pull_request:
    branches: ["step-1", "step-2", "step-3"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: |
          npm install
          npm test
          npm run build
